### ISSUE TITLE
Checklist for moving from GitLab

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#1290]
This is the checklist for moving from gitlab

I've temporarily placed the repository into "moderation mode" so for now new issues and PRs are disabled while I work everything out

- [x] import issues from gitlab
    - this was **unfortunately** noisy and error-prone, if I ever do this again I'll probably write a different script.  I used [this thing](https://github.com/piceaTech/node-gitlab-2-github) however it @-mentions people and includes a lot of noisy unnecessary comments and doesn't have good error handling, and a bunch of other stuff too
- [x] enable mirroring on gitlab
- [x] disable new issue / PR creation on gitlab
    - I didn't find the right setting for this so for now MRs and Issues are invisible to non-collaborators.  Ideally I'd like them to be read-only. 🤷 
- [x] set up CI
- [x] fix changelogs
- [x] fix references to gitlab in docs / code
- [x] fix repository description
- [x] add issue template
- [x] close issues which should have been closed but weren't for some reason
- [x] review open PRs

**Comment by asottile** [comment]
I believe this is completed, I've unlocked the repo -- happy coding!

**Comment by philgyford** [comment]
The "Homepage" link on https://pypi.org/project/flake8/ still points to the gitlab repo.
