### ISSUE TITLE
List of plugins broken by 3.0.0

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#504]
In GitLab by @sigmavirus24 on Jun 26, 2016, 05:21

# Broken Plugins

- [x] flake8-import-order (fix proposed: https://github.com/public/flake8-import-order/pull/75)
- [x] pep8-naming (fixed in 0.4.1)
- [ ] flake8-putty (see: https://github.com/jayvdb/flake8-putty/issues/15, https://github.com/jayvdb/flake8-putty/issues/14)
- [x] flake8-copyright (see: https://github.com/savoirfairelinux/flake8-copyright/issues/7) (fixed in 0.2.0)
- [x] ebb-lint (see: https://github.com/habnabit/ebb-lint/issues/2)
- [ ] flake8-author (use of `config_options`)
- [x] flake8-mock (optional parameter of `builtins` that is unused, see #151, fixed by 2d3e277)
- [x] flake8-debugger (optional parameter of `builtins` that is unused, see #151, fixed by 2d3e277)
- [x] flake8-commas (optional parameter of `builtins` that is unused, see #151, fixed by 2d3e277)
- [x] flake8-quotes (see: https://github.com/zheller/flake8-quotes/issues/29, resolved by: https://github.com/zheller/flake8-quotes/pull/34)

# Reason

Most of these plugins are most likely register options to be parsed from configuration. To fix these read: http://flake8.pycqa.org/en/latest/plugin-development/cross-compatibility.html#option-handling-on-flake8-2-and-3

If these plugins are failing because they import something from Flake8, please describe the traceback below so we can figure out what needs to be added to our publicly supported API.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jun 26, 2016, 05:30

Changed title: **{-Master l-}ist of plugins broken by 3.0.0** → **{+L+}ist of plugins broken by 3.0.0**

**Comment by asottile** [comment]
In GitLab by @The-Compiler on Jun 26, 2016, 07:32

Plugins I noticed the same config issue with:

- [ebb-lint](https://github.com/habnabit/ebb-lint/issues/2)
- [flake8-future-import](https://github.com/xZise/flake8-future-import/issues/8)
- [flake8-copyright](https://github.com/savoirfairelinux/flake8-copyright/issues/7)
- [flake8-putty](https://github.com/jayvdb/flake8-putty/issues/14) (though it's probably not necessary with 3.0 anymore, also see [issue 15 there](https://github.com/jayvdb/flake8-putty/issues/15))

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jun 28, 2016, 06:38

Marked the task **flake8-copyright (see: https://github.com/savoirfairelinux/flake8-copyright/issues/7)** as completed

**Comment by asottile** [comment]
In GitLab by @xZise on Jun 29, 2016, 04:15

Also seeing issues in:

* [flake8-quotes](https://github.com/zheller/flake8-quotes) (reported as [bug 29](https://github.com/zheller/flake8-quotes/issues/29))
* ~~[flake8-string-format](https://github.com/xZise/flake8-string-format) (same issue as flake8-future-import mentioned by @The-Compiler, and also my project so I can apply my fix to both)~~ This is actually not really the case as the currently released script doesn't break, but my development version did.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jul 20, 2016, 07:46

Marked the task **flake8-import-order (fix proposed: https://github.com/public/flake8-import-order/pull/75)** as completed

**Comment by asottile** [comment]
In GitLab by @Jc2k on Aug 18, 2016, 02:23

[flake8-isort](https://github.com/gforcada/flake8-isort) was also broken - reported as [bug 13](https://github.com/gforcada/flake8-isort/issues/13).  Looks like its the option registering and the style guide stuff.

**Comment by asottile** [comment]
In GitLab by @mihaic on Sep 6, 2016, 22:28

[`flake8-print`](https://github.com/JBKahn/flake8-print) has its codes disabled by default because of the naming of its `setuptools` entry point. [PR #17](https://github.com/JBKahn/flake8-print/pull/17) is supposed to fix it, but needs input from someone knowledgeable about `flake8`: what should the entry point be named if the plugin codes use a prefix also used by other plugins?

**Comment by asottile** [comment]
In GitLab by @pjacock on Sep 7, 2017, 08:10

According to the linked issue, ``ebb-lint`` now works on flake8 v3

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Sep 8, 2017, 04:27

marked the task **ebb-lint (see: https://github.com/habnabit/ebb-lint/issues/2)** as completed

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Oct 20, 2018, 10:40

closed
